apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-cache-nfs-pv
  labels:
    storage-owner: jenkins
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  volumeMode: Filesystem
  mountOptions:
    - nfsvers=4.2
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 192.168.123.10
    path: /srv/nfs/k8s/maven-cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-cache
  namespace: ci
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  resources:
    requests:
      storage: 10Gi
